import { openai, supabase } from "./config.js";
import podcasts from "./content.js";

// User query about podcasts
const query = "Orca of Orcas";
main(query);

/** Create embeddings representing the input text */
async function main(input) {
  const embeddingResponse = await openai.embeddings.create({
    model: "text-embedding-ada-002",
    input,
  });

  // The vector generated by openAI
  const embedding = embeddingResponse.data[0].embedding;

  // Query supabase for nearest vector match
  const { data } = await supabase.rpc("match_documents", {
    query_embedding: embedding,
    match_threshold: 0.5,
    match_count: 1,
  });
  console.log(data[0].content, data[0].similarity);
}
